# Site settings
title: Taehan Kim
baseurl: ""
url: "https://thKimm.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Taehan Kim
  desc: AI, Signal Processing, Audio/Speech Enhancement
  email: taehank@gmail.com
  selfie: assets/img/home/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: thKimm
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/taehan-kim-4a2785317/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/work/page:num/"
paginate: 10
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

# description
description: "[Pr] : Project, [C] : Conference, [J] : Journal, [Pt] : Patent"